- name: Host HTML/CSS locally using Nginx
  hosts: localhost
  become: true

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Copy HTML/CSS files to Nginx web root
      copy:
        src: /mnt/e/devops/html/
        dest: /var/www/html/
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Copy images to Nginx web root
      copy:
        src: /mnt/e/devops/images/
        dest: /var/www/html/images/
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Ensure Nginx is running
      service:
        name: nginx
        state: started
        enabled: yes
